environment:
  matrix:
    - nodejs_version: '6'

cache:
  - "%LOCALAPPDATA%/Yarn"
  - node_modules

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm test

build: off
